#!/data/$USER/venvs/pybdsf/bin python3
'''
module load Python/3.8.6-GCCcore-10.2.0
source /data/$USER/venvs/pybdsf/bin/activate
'''

import bdsf
import sys
import os
import numpy as np

def extract_sources(in_img):

    infile = str(in_img)[2:-1][:-1] # this is aimed to remove the list [] generated by python args eg hello, is given as ["hello"]
    
    #Run pybdsf
    img = bdsf.process_image(infile)
    
        
    print('=== Export images ===')
    # TODO: the image fit does not display the images from the hpc eviron as expected
    img.show_fit()
   
    # Export the files   
    
    img.write_catalog(outfile = infile +'.cat.fits',catalog_type = 'srl',format = 'fits',correct_proj = 'True',clobber = True)
    img.export_image(outfile = infile +'.cho.fits',img_type = 'ch0',img_format = 'fits',clobber = True)
    img.export_image(outfile = infile +'.rms.fits',img_type ='rms',img_format = 'fits',clobber = True)    
    img.export_image(outfile = infile +'.mean.fits',img_type = 'mean',img_format = 'fits',clobber = True)
    img.export_image(outfile = infile +'.resid.fits',img_type = 'gaus_resid',img_format = 'fits',clobber = True)
    img.export_image(outfile = infile +'.bdsfmask.fits',img_type = 'island_mask',img_format = 'fits',clobber = True)
    img.write_catalog(outfile = infile +'.cat.reg',catalog_type = 'srl',format = 'ds9',correct_proj = 'True',clobber = True)
    

if __name__ == "__main__":
    in_img = sys.argv[1:]
    extract_sources(in_img)
