#!/data/$USER/venvs/pybdsf/bin python3
import sys
import numpy as np
import astropy.io.fits as fits
import matplotlib.pyplot as plt
from astropy.utils.data import get_pkg_data_filename
from astropy.table import Table
from astropy.wcs import WCS
def func(var):
    var = str(var)[2:-1][:-1] # this is aimed to remove the list [] generated by python args eg hello, is given as ["hello"]
    print(var)
    #image_file = get_pkg_data_filename(var)
    #print(fits.info(image_file))
    hdulist = fits.open(var)
    img = hdulist[0].data
    print(img.shape)
    print(WCS(hdulist[0].header))
    
    '''
    hdulist = fits.open(var)
    data = hdulist[0].data
    plt.imshow(data, cmap=plt.cm.viridis)
    plt.xlabel('x-pixels (RA)')
    plt.ylabel('y-pixels (Dec)')
    plt.colorbar()
    plt.show()
    '''
    
if __name__ == "__main__":
    var = sys.argv[1:]
    func(var)
